# --------------------------------------------------
# Site settings
# --------------------------------------------------

# Color
color:
  default: "#33333D"
  link: "#FFBE5B"

# Background Image
background_image:

# Favicon
favicon:
  small: /images/icons/favicon-16x16.ico
  medium: /images/icons/favicon-32x32.ico
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Preview
preview:
  enable: true
  model: wave  # wave | cloud
  welcome_image: /images/theme/welcome-image.jpg
  motto:
    default: 当我抬起头，它已不知去向
    color: '#ffffff'
    api:  # http://localhost:3000/api/motto

# Menu
menu:
  home: / || 首页
  galleries: /galleries || 摄影
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  github: https://github.com/iaosee || icongithub-fill || '#24292E'
  email: mailto:iaosee@outlook.com || iconmail

# Loading
loading: /images/theme/loading.gif

# Fab (FloatActionButton)
fab:
  enable: true
  alwaysShow: false

# Gray (Mourning Mode)
gray:
  enable: false

# Color Mode
color_mode:
  enable: true

# --------------------------------------------------
# Post settings
# --------------------------------------------------

# Post image
post_image:
  random: local # galleries
  default: /images/theme/post-image.jpg

# Donate
donate:
  enable: false
  alipay:
  wechat:

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # markdown text

# --------------------------------------------------
# Page settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# --------------------------------------------------
# Comment settings
# --------------------------------------------------

comments:
  enable: true
  type: valine
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId: QRsYxiOY3VGeVhkqx7yJiz0U-gzGzoHsz
  appKey: 1ygwFPYG8IbvlgnrnNXrNeNe
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  appKey:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Daovoice
daovoice:
  enable: true
  appId: fb486b7c  # app_id

# Lazyload
lazyload:
  enable: true
  onlyPost: false
  loading: /images/theme/loading.gif

# LeanCloud
leancloud:
  enable: false
  appId: QRsYxiOY3VGeVhkqx7yJiz0U-gzGzoHsz
  appKey: 1ygwFPYG8IbvlgnrnNXrNeNe
  serverURLs:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# --------------------------------------------------
# Script settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: //at.alicdn.com/t/font_1445822_onl0g0h21np.css

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: fa215b20eccf04179a4d316087693164 # id
  google: # id
  tencent: # id
  cnzz: # id

# Custom
custom:
  head:
  foot:
  css:
  js:
